### ISSUE TITLE
Any hints on how to bundle spellfix1?

### ISSUE THREAD

**Issue by saibotma** [simolus3/sqlite3.dart#319]
Thanks for this awesome package. I want to build a great search experience and required `spellfix1` for this. According to the [docs](https://drift.simonbinder.eu/generation_options/#available-extensions) it is not included by default.

You already gave some hints on how to include it [here](https://github.com/simolus3/sqlite3.dart/issues/152#issuecomment-1490797080) and according to the changelog it was [bundled](https://github.com/simolus3/sqlite3.dart/blob/48706606ec97e2b4c09d69a5466c961d630e2b65/sqlite3_flutter_libs/CHANGELOG.md?plain=1#L124) some time ago.

Do you have some more detailed explanations on how one can bundle it for iOS, Android & Web?

**Comment by CaptainDario** [comment]
As the generator already includes spellfix1 I am curious if there is any chance that it will be bundled with libs?

**Comment by CaptainDario** [comment]
Thank you!
I am considering building SQLite with all the extensions included, is it possible to use the native assets feature to include my own .dll etc.?

Would there be any downsides? I need support for native and web.

**Comment by simolus3** [comment]
Native assets unfortunately only work on, well, native platforms.

On the web, compiling everything into a custom single bundle is the only approach at the moment. But I think it should be feasible to load extensions there as well by sharing memory between two WASM bundles. I can take a look at adding an API for that!

**Comment by CaptainDario** [comment]
Well the native assets being on native platforms makes sense. Sometimes things are too obvious 😅

I am gonna try the native assets as you explained before in the coming days and adding extension loading for web would be awesome!

**Comment by saibotma** [comment]
@CaptainDario it would be great if you could document your experiences and the steps you take. I’m sure this will be helpful for others (including me 😃) in the future.

**Comment by simolus3** [comment]
> After commenting the problematic lines, this, throws

I've removed them from the snippet.

> Could you also please make a new release of the native assets package that bumps the hooks dependency?

Done, thanks for the heads up!

>  If I understood correctly DynamicLibrary.open(), should not be used anymore, right?

Correct. There's a new `sqlite3Native` getter you can use instead (it's also supported by drift, you can pass the `sqlite3: () => sqlite3Native` option to `NativeDatabase`. That implementation uses [this](https://github.com/simolus3/sqlite3.dart/blob/bccb6c4a0ccb0d12fa4a6142975508fbd7dcf337/sqlite3/lib/src/ffi/bindings.dart#L70-L78), which delegates to [this file](https://github.com/simolus3/sqlite3.dart/blob/main/sqlite3/lib/src/ffi/generated/native.dart) using `@Native` annotations instead of ever loading a `DynamicLibrary` manually.

The error about not being able to contribute assets to other packages is very annoying though - I've opened https://github.com/dart-lang/native/issues/2605 for a discussion.

That said, a viable workaround may be to only compile the extensions you're interested in instead of all of SQLite (you should be able to compile e.g. `spellfix1.c` into a shared library as well). Then you don't have to patch SQLite bindings and load the extension through its main function (like described in my original comment - let me know if I should provide more details on this).

**Comment by simolus3** [comment]
Is this on macOS? The default sqlite library that ships on macOS does not support extension (it's been patched out by Apple). If you're using the native-assets variant (`sqlite3Native.ensureExtensionLoaded()`), that shouldn't be an issue.

**Comment by CaptainDario** [comment]
Oh, wow, thank you, it loaded!

```dart
final ext = SqliteExtension.inLibrary(dl, "sqlite3_vec_init");
sqlite3Native.ensureExtensionLoaded(ext);

final db = sqlite3.openInMemory();
db.execute('create virtual table vec_examples using vec0(sample_embedding float[8]);');
```

But I am still getting an error at the db.execute

```
Testing SQLite-vec loaded [E]                                                                                                                                                                                                                                                                                                                                                                                             
  SqliteException(1): while executing, no such module: vec0, SQL logic error (code 1)
    Causing statement: create virtual table vec_examples using vec0(sample_embedding float[8]);, parameters: 
  package:sqlite3/src/implementation/exception.dart 95:3  throwException
  package:sqlite3/src/implementation/database.dart 306:9  DatabaseImplementation.execute
  test/libs/test_libs_loaded.dart 28:8                    main.<fn>
```

Do I need to load the module or am I doing something wrong?

**Comment by simolus3** [comment]
You're using `sqlite3Native` to load the extension and `sqlite3` (using `DynamicLibrary`) to open the database. These will talk to a different SQLite library (which is [fairly dangerous btw](multiple_copies_of_sqlite_linked_into_the_same_application)). So you would have to use `sqlite3Native` everywhere in this case.

You could add `open.overrideForAll(() => throw 'should not use dynamically-loaded sqlite libraries')` early in `main` to verify that you're not missing a `sqlite3` use somewhere.

**Comment by CaptainDario** [comment]
Thank you for all your tips! I got all my extensions to load.

However, with the current approach, bundling all of them will be quite annoying and brittle.
Therefore, I wanted to ask how I can load them when bundled as a CodeAsset.
In https://github.com/dart-lang/native/issues/2605 you mentioned that there is a way using
`@Native` and `sqlite3_auto_extension(Native.addressOf(sqlite3_spellfix_init))`.

I got my .dylib bundled as my `native-assets.yaml` shows

```yaml
...
"native-assets": {
    "macos_arm64": {
      "package:sqlite3_native_assets/sqlite3_native_assets.dart": [
        "absolute",
        "/path/to/project/db/.dart_tool/lib/libsqlite3.dylib"
      ],
      "package:db/vec0.dylib": [
        "absolute",
        "/path/to/project/db/.dart_tool/lib/vec0.dylib"
      ]
    }
  }
```

But I cannot figure out how to load that extension from the native asset.
Because you mentioned in the other issue, you will be adding some examples on how to do this. It would be very nice if you could also update here when they are available.

Thank you again very much for all your effort!

**Comment by simolus3** [comment]
I have added one for the vector extension you're using [here](https://github.com/simolus3/sqlite3.dart/tree/main/sqlite3/example/custom_extension_native_assets), let me know if that helps!

**Comment by CaptainDario** [comment]
Thank you so much, it works now!

To summarize how to load the spellfix extension I did

### 1. Compile the extension
For this the SQLite sources and the spellfix extension need to be downloaded and compiled.
You can find the sources on the SQLite website and compile them (on MacOS) using this

`gcc -I./$(SRC_DIR) -g -fPIC -shared ./$(EXT_DIR)/spellfix.c -o ./$(BUILD_DIR)/spellfix.dylib`

### 2. Setup `CodeAssets`
Currently, they are hidden behind this flag: `--enable-experiment=native-assets`, but this should not be necessary anymore after the next Dart release.
With this, you need a `hook/build.dart` which tells Dart to bundle the library. Something like this

```dart
void main(List<String> args) async {
  
  await build(args, (input, output) async {

    String extensionPath = "/path/to/your/spellfix_library";
    String extensionName = "spellfix"

    // Add the code asset to the build output.
    for (var extensionName in extensionNames) {
      output.assets.code.add(
        CodeAsset(
          package: input.packageName,
          name: 'extensions/sqlite_${extensionName}_extension.dart',
          linkMode: DynamicLoadingBundled(),
          file: Uri.parse(p.join(extensionPath, '${extensionName}.dylib'))
        )
      ); 
    }
    
  });
}
```

### 3 Link the library with dart

Create a file called `sqlite_spellfix_extension.dart` and add this code

```dart
// ignore_for_file: non_constant_identifier_names

import 'dart:ffi';

import 'package:sqlite3/sqlite3.dart';

@Native<Int Function(Pointer<Void>, Pointer<Void>, Pointer<Void>)>()
external int sqlite3_spellfix_init(
  Pointer<Void> db,
  Pointer<Void> pzErrMsg,
  Pointer<Void> pApi,
);

extension LoadSpellfixExtension on Sqlite3 {
  void loadSqliteSpellfixExtension() {
    ensureExtensionLoaded(
      SqliteExtension(
        Native.addressOf<
          NativeFunction<
            Int Function(Pointer<Void>, Pointer<Void>, Pointer<Void>)
          >
        >(sqlite3_spellfix_init).cast(),
      ),
    );
  }
}
```

### 4 Consume the extension

Somwhere

``` dart
import 'package:sqlite3/native_assets.dart';
import 'package:your/package/extensions/sqlite_spellfix_extension.dart';

sqlite3Native.loadSqliteSpellfixExtension();
```

@saibotma I hope this helps! In case your struggle with this, the example from @simolus3 [here](https://github.com/simolus3/sqlite3.dart/tree/main/sqlite3/example/custom_extension_native_assets) will solve any issues you have.

**Comment by CaptainDario** [comment]
@simolus3 Will drift automatically use the native assets when they are included in the project?

**Comment by simolus3** [comment]
Not at the moment (but I'll do my best to make native assets the default soon after they're stable). On the `NativeDatabase` class, there's a [sqlite callback](https://pub.dev/documentation/drift/latest/native/NativeDatabase/NativeDatabase.html). If you set that to `() => sqlite3Native`, drift would use the native assets variant of SQLite.

**Comment by CaptainDario** [comment]
Thank you!
@saibotma  I guess this issue can be closed then?
